# Generated by Django 3.0.3 on 2020-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='private_key',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
