# Generated by Django 3.0.3 on 2020-05-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT1', '0002_auto_20200529_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='file',
        ),
    ]
