# Generated by Django 3.0.3 on 2020-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT1', '0003_remove_dispositivo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='estado_token',
            field=models.CharField(default='---', max_length=50),
        ),
    ]
