# Generated by Django 3.0.3 on 2020-02-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioIoT', '0004_auto_20200221_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nombregrupo', to='ServicioIoT.GrupoDispositivo', to_field='nombre'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='grupoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idgrupo', to='ServicioIoT.GrupoDispositivo'),
        ),
        migrations.AlterField(
            model_name='grupodispositivo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
