# Generated by Django 3.0.3 on 2020-02-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioIoT', '0005_auto_20200221_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='grupoid',
        ),
    ]
