# Generated by Django 3.0.3 on 2020-04-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioIoT', '0012_auto_20200408_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extradata',
            old_name='user',
            new_name='user_id',
        ),
    ]
