# Generated by Django 3.0.3 on 2020-04-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioIoT', '0014_auto_20200408_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extradata',
            old_name='user_id',
            new_name='userid',
        ),
    ]
