# Generated by Django 3.0.3 on 2020-05-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioIoT', '0015_auto_20200408_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='private_key',
            field=models.CharField(default='Hola', max_length=5000),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='token',
            field=models.CharField(default='Esto no es un token', max_length=100),
        ),
    ]
