# Generated by Django 3.0.3 on 2020-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioIoT', '0016_auto_20200523_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='datos',
            field=models.CharField(default='Datos del dispositivo', max_length=10000),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='link',
            field=models.CharField(default='localhost.com', max_length=200),
        ),
        migrations.AddField(
            model_name='extradata',
            name='expires_in',
            field=models.IntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='extradata',
            name='token_update_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='private_key',
            field=models.CharField(default='----', max_length=5000),
        ),
    ]
