# Generated by Django 3.0.3 on 2020-05-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicioIoT', '0018_auto_20200528_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='token',
            field=models.CharField(default='Esto no es un token', max_length=1000),
        ),
    ]
